repositories:
  - "https://mobb-pf.github.io/helm-repository"
  - git@github.com:redhat-blackbelt-online-boutique/online-boutique-cd.git

microenvironments:
  - name: ob
    requests:
      cpu: 30
      memory: 22Gi
    limits:
      cpu: 30
      memory: 22Gi
    projects:
      - name: dev
        labels: |
          name: ob-dev
          argocd.argoproj.io/managed-by: openshift-gitops



















